### ISSUE TITLE
How to do precompilation / on-the-fly precompilation?

### ISSUE THREAD

**Issue by TerraX-net** [sunng87/handlebars-rust#158]
If one has a "Content-Security-Policy: default-src 'self'", you have to use precompiled templates, otherwise one has to allow unsafe-eval which isn't security wise.

So I came to http://handlebarsjs.com/precompilation.html and handlebars-rust and thought: "hey, I would like to use on-the-fly precompilation for development and into-a-file precompilation for production behind hyper with tokio-rustls".

I looked for Template::compile ... and saw "[Removed] to_string of Template and TemplateElement which is unnecessary and contains issue" in your Changelog.
Now I am a bit baffled what to do. Do you have a tip?

**Comment by sunng87** [comment]
Hi @TerraX-net ,

Internally, this library compiles template when you caall `register_template_string". The template will be parsed and transformed into an internal data structure. All the render tasks for registered templates will benefit from this process, because there will be no parse cost any more. For a typical web application, this is done during server startup. At the moment there is no "into-a-file" compilation for handlebars-rust, which we don't have a strong need for. 

For on-the-fly rendering, there is a method called `template_render` accepts template string and data. The template string need to be parsed every time you call this function.

`Template::compile` as a public API is removed in previous release, it's now done in `register_template_string`. So you don't need to worry about that.

**Comment by TerraX-net** [comment]
Thank you, @sunng87.
So if I unterstand it right, handlebars-rust can output a rendered page, made from a template and json object.
I wanted to do rendering in the browser with handlebars.runtime-latest.js to save bandwith by having a precompiled template in the browser cache. It has to be precompiled for performance reasons and to prevent an "unsafe-eval" in the Content-Security-Policy (HTTP response header).
We planned our rust application to serve precompiled templates for modern browsers, but completely rendered pages for search bots. For the first task we may now use http://handlebarsjs.com/precompilation.html and for the second task we would use handlebars-rust.

**Comment by sunng87** [comment]
Yes, currently handlebars-rust is mostly for server-side render. If you compile rust to WebAssembly then you may use it in browser.
