### ISSUE TITLE
Consider using rustc_serialize::json::encode to obtain json

### ISSUE THREAD

**Issue by hugoduncan** [sunng87/handlebars-rust#19]
Rather than force every structure to implement the `ToJson` trait, it might be preferable to allow users to just add a `#[derive(RustcEncodable)]` on their structs, and handlebars can obtain a JSON value via the `rustc_serialize::json::encode` function.

**Comment by Vayn** [comment]
+1

And according to this post: [What's the difference between the “serialize” and “rustc-serialize” crates?][1], I recommend to use [Serde][2] and its macros to serialize/deserialize a struct to/from JSON instead of _rustc-serialize_.

  [1]: http://stackoverflow.com/questions/28456813/whats-the-difference-between-the-serialize-and-rustc-serialize-crates/28457675#28457675
  [2]: https://github.com/erickt/rust-serde

**Comment by hugoduncan** [comment]
I can second the recommendation for Serde, although it does require rust nightly to use it.

**Comment by sunng87** [comment]
Note that we don't actually serialize data to JSON. We just use the `ToJson` trait as a type system. Because handlebars is designed against JavaScript, whose type system isn't fully compatible with Rust. Currently, `ToJson` is a good way to convert Rust types into JavaScript types. 

Yes, we need a macro for users to generate their `ToJson` impl easily.

**Comment by Vayn** [comment]
Thanks, I understand why you use `Json` enum and `ToJson` trait for transforming Rust type and JavaScript type. It is little twisted for the purpose though... Macro is a better and clearer way.

**Comment by sunng87** [comment]
@Vayn patches are always welcomed :-)

**Comment by hugoduncan** [comment]
Another possibility, when using serde at least, would be to write your own `Serializer` implementation that returned a `BTreeMap` of values.  This would remove the need to implement `ToJson` and the need for a custom macro.

**Comment by sunng87** [comment]
@hugoduncan I didn't look into Serde, is it easier to implement Serializer of Serde than ToJson of rustc-serialize? 

Because most `ToJson` implementation will be: create a map, put every field into it. Perhaps we can find some meta-programming techniques to deal with this. Not sure if Rust has something for that.

**Comment by hugoduncan** [comment]
@sunng87 The `Serializer` would be something that rust-handlebars would implement.  Users would then just mark structs with `#[derive(Serialize)]`.

**Comment by sunng87** [comment]
@hugoduncan Iooked at Serde, I would like to implement a  custom derive for handlebars that generates `ToJson` implementation. It would be compatible with current type system, but also reduce repeated `ToJson` impl.

**Comment by sunng87** [comment]
@hugoduncan @Vayn check out [tojson_macros](https://github.com/sunng87/tojson_macros) I just made for generating default `ToJson` imp.

**Comment by Vayn** [comment]
I'm still learning how to make a procedural macro for custom struct.

@sunng87 You're amazing! :+1:

**Comment by sunng87** [comment]
@Vayn :)

I'll close this for now. Feel free to reopen if there's any question.
