### ISSUE TITLE
subexpression problem

### ISSUE THREAD

**Issue by azerupi** [sunng87/handlebars-rust#32]
Hi, I have been using handlebars-rust in my project: [mdBook](https://github.com/azerupi/mdBook) and before I bother you with my problem I want to thank you for your work on this crate :+1: 

So it's my first time using handlebars, so maybe i am doing something wrong but I have this code:

```handlebars
{{#if (previous)}}
    <a href="{{#previous}}{{/previous}}" class="nav-chapters previous">
        <i class="fa fa-angle-left"></i>
    </a>
{{else}}
    {{#previous}}{{/previous}}
{{/if}}
```            
And basically what I am trying to do is hide the block if the `previous` helper returns `""`.
But it was always hidden. *I have added the else block only to confirm that `previous` did return something.*

Could this be a bug or am I doing something stupid?

**Comment by sunng87** [comment]
Thanks for using handlebars-rust.

Here the `(previous)` subexpression returns an empty string `""`, then `if` will treat it as path instead of value. That means `if` will check to current context.

I think a better solution is to make `previous` a block helper. Your template will be like:

```handlebars
{{#previous}}
  <a href="{{link}}" class="nav-chapters previous">
    <i class="fa fa-angle-left"></i>
  </a>
{{/previous}}
```

And in the previous helper, you need to check if the previous is existed. 

If true,

Extending the context with a BTreeMap of {link: ...} by calling `ctx.extend(map)`. (ctx.extend is coming in next release)

Then render the inner template by `_h.template.render(c, r, rc)` (where _h is the helper, r is the handlebars registry and rc is render context).

If the previous link doesn't exist, just do nothing.

**Comment by sunng87** [comment]
Just release 0.9.3 with `context.extend`. Don't be hesitate to contact me if you have any other questions. It's great for me to see more and more use case of this library.

**Comment by azerupi** [comment]
Thanks a lot :)

I am really not familiar with handlebars, but I will try what you said and if I have a problem I will come back ;) Do you have a doc for handlebars-rust?

> Here the (previous) subexpression returns an empty string ""

Could you explain why that happens? Because when used like `{{#previous}}{{/previous}}` it does return something.

**Comment by azerupi** [comment]
Hey @sunng87,

I have tried what you said, it mostly works but I can't extend the context correctly.

So I have this bit of code

```rust
let mut previous_chapter = BTreeMap::new();

previous_chapter.insert("title".to_string(), previous.get("name").unwrap().to_json()); 
previous_chapter.insert(
    "link".to_string(),
    path_to_root.join(
        Path::new(previous.get("path").unwrap())
            .with_extension("html")
    ).to_str().unwrap().to_json()
);

// Inject in current context
c.extend(&previous_chapter);

// Render template
_h.template().unwrap().render(c, r, rc).unwrap();
```

And in my template I used

```handlebars
{{#previous}}
  <a href="{{link}}" class="nav-chapters previous">
    <i class="fa fa-angle-left"></i>
  </a>
{{/previous}}
```

But for whatever reason `{{link}}` is `null`

Do you know why?

**Comment by sunng87** [comment]
You should take the return value as new context:

```rust
// Inject in current context
let new_context = c.extend(&previous_chapter);



// Render template
_h.template().unwrap().render(new_context, r, rc).unwrap();
```

Check the test case for example: https://github.com/sunng87/handlebars-rust/blob/master/src/context.rs#L269

To answer your previous question, the first argument of `if` is a path instead of a value. Handlebars will look up the context with your subexpression result, so it will always return nil and never enter `if` block.

**Comment by azerupi** [comment]
> You should take the return value as new context

Works like a charm! 
Thank you very much for your help and keep up the good work :+1:
