### ISSUE TITLE
compatibility: escape functions are not applied to template tags with helper function

### ISSUE THREAD

**Issue by tnak** [sunng87/handlebars-rust#361]
For example, using this helper function
```rust
handlebars_helper!(to_tag: |x: str| { format!("<{}>", x) });
```
render this template
```handlebars
{{to_tag tag}}
```
with value `tag = "br"` and registering `html_escape`, you will get output `<br>` instead of  `&lt;br&gt;` that original handlebars.js does. Using "unescaped" tag (`{{{to-tag tag}}}`) results in `TemplateError`.

FYI: I accidentally found workaround. Using parentheses like `{{(to-tag tag)}}` solved my problem. `{{(to-tag tag)}}` and `{{{(to-tag tag)}}}` resulting in the rendered text `&lt;br&gt;` and `<br>` respectively. But these templates seem to result in error in the original JS version.

**Comment by sunng87** [comment]
Thanks for reporting. This is because of the issue we deal with `{{` style helper call and `{{{`. This has to be fixed and I will add to my backlog.

Actually the workaround should not work if the implement was correct. We should use the out of `(to-tag tag)` as reference to resolve in current context.
