### ISSUE TITLE
Auto-reload for Partials

### ISSUE THREAD

**Issue by waldreiter** [sunng87/handlebars-rust#432]
Hello,

in `dev_mode` auto-reload works for the main template. But for partials it does not work for me. Am I missing something or is this a bug?

I have version 4.0.0-beta.2 installed.

By the way, I use *handlebars-rust* together with *browser-sync* and *tailwindcss*. That is a very nice and modern way of front-end development. But for making large websites it needs auto-reload for partials.

**Comment by sunng87** [comment]
Good catch. Partials seem to be a missing part from dev_mode. Because we loads the main template from disk but use the cached partials. This will be supported before 4.0 and needs some work to refactor the partials system.

> By the way, I use handlebars-rust together with browser-sync and tailwindcss. That is a very nice and modern way of front-end development. But for making large websites it needs auto-reload for partials.

It's really nice to hear about your workflow. If you have a repo of your setup please kindly let me know.

**Comment by cody** [comment]
> It's really nice to hear about your workflow. If you have a repo of your setup please kindly let me know.

[Browsersync](https://www.browsersync.io) reloads the website in the browser every time a template changes or the rust server restarts.

[Tailwind](https://tailwindcss.com) is a popular css framework. It works great with handlebars, because[ it just looks for strings](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html).

This is my *package.json*:
```js
{
	"devDependencies": {
		"autoprefixer": "^10.2.5",
		"browser-sync": "^2.26.14",
		"postcss-cli": "^8.3.1",
		"tailwindcss": "^2.1.2"
	},
	"scripts": {
		"build": "NODE_ENV=production postcss templates/tailwind.css -o public/css/tailwind.css",
		"watch": "postcss templates/tailwind.css -o public/css/tailwind.css --watch",
		"serve": "browser-sync start --proxy 127.0.0.1:8080 --files ['templates/**/*', 'public/**/*']"
	}
}
```

**Comment by sunng87** [comment]
@waldreiter this should be fixed on our latest master. Let me know if you have any issue with it
