### ISSUE TITLE
How to create a block helper with a macro?

### ISSUE THREAD

**Issue by mladedav** [sunng87/handlebars-rust#491]
The README says we can also create block helpers but I couldn't find an example, the documentation just mentions which arguments can be passed to the closure, but I can't find anything about evaluating the block inside.

Can an example be provided? I haven't even found any tests concerning this, all tests use just simple parameters and implement functions like "is less than 10".

**Comment by sunng87** [comment]
hi @mladedav , creating block helper with macro is not supported because block helpers contains more logic than just operating with parameters. You can find example by checking the implementation of [`if`](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_if.rs) and [`each`](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_each.rs).

**Comment by mladedav** [comment]
Sorry, I seem to have misread the README, it just says that we can create block helpers, but doesn't mention the macro at that point.

Thank you for the pointer.
