### ISSUE TITLE
serde vs rustc_serialize

### ISSUE THREAD

**Issue by mikedilger** [sunng87/handlebars-rust#50]
I've been told by Nick Cameron and James Miller that the `rustc_serialize` crate is long past expired and that serde should be used instead.

It should probably be setup as feature options (choose either rustc_serialize or serde) so downstream users aren't forced to move over to serde immediately.

If I get a chance I'll give it a try and submit a PR, but don't expect anything for at least a few days

**Comment by sunng87** [comment]
I did have the same idea (#40) to make the `Context` works for both serde and rustc-serialize. I found serde has [similar type system](https://github.com/serde-rs/json/blob/master/json/src/value.rs) so we can surely port our `Context` to serde. The issue is I hope we can keep backward compatibility for current API and especially for existed helpers. Feature option is a good idea, we will deprecated current rustc_serialize impl at some time by making serde as default feature.

Another idea is to roll our own javascript type system to prevent the confusion like "do you serialized data to JSON in handlebars". Also we need some enhanced expression support for this system, that is, to move most code of `Context::navigate` into a standalone module and add some features. For example:

* if `a` is a `Vec`, I hope the expression `a.length` could return the size of the vector
* if `b` is a `BTreeMap`, expression like `b["key"]` could access the value just like it was in javascript


Above are my own thoughts. Any kind of suggestion or help is always welcomed. Thanks!

**Comment by sunng87** [comment]
@mikedilger Any updates on this? I'm planning to add a feature to use serde json types. If you have already been working on that, please kindly let me know.

**Comment by mikedilger** [comment]
No I haven't done anything yet

**Comment by sunng87** [comment]
I created a branch and had some early work:
https://github.com/sunng87/handlebars-rust/tree/feature/serde-feature

**Comment by sorenhoyer** [comment]
Cool, thanks - Looking forward for serde_json support in handlebars-iron in the near future as well. :-)
